// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.LogicaAccesoDatos;

#nullable disable

namespace Sistema.LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimientos");

                    b.HasDiscriminator().HasValue("Movimiento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TipoGastos");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TipoIngresos");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Entrada", b =>
                {
                    b.HasBaseType("Sistema.LogicaNegocio.Entidades.Movimiento");

                    b.Property<int>("TipoIngresoId")
                        .HasColumnType("int");

                    b.HasIndex("TipoIngresoId");

                    b.HasDiscriminator().HasValue("Entrada");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Salida", b =>
                {
                    b.HasBaseType("Sistema.LogicaNegocio.Entidades.Movimiento");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int");

                    b.HasIndex("TipoGastoId");

                    b.HasDiscriminator().HasValue("Salida");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Movimiento", b =>
                {
                    b.HasOne("Sistema.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoGasto", b =>
                {
                    b.HasOne("Sistema.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany("TiposGastos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoIngreso", b =>
                {
                    b.HasOne("Sistema.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany("TiposIngresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Entrada", b =>
                {
                    b.HasOne("Sistema.LogicaNegocio.Entidades.TipoIngreso", "TipoIngreso")
                        .WithMany("Entradas")
                        .HasForeignKey("TipoIngresoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoIngreso");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Salida", b =>
                {
                    b.HasOne("Sistema.LogicaNegocio.Entidades.TipoGasto", "TipoGasto")
                        .WithMany("Salidas")
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoGasto", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.TipoIngreso", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Sistema.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("TiposGastos");

                    b.Navigation("TiposIngresos");
                });
#pragma warning restore 612, 618
        }
    }
}
